name: module-tests-develop

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests.yml@main
    with:
      humhub-ref: >-
        ['develop']
      php: >-
        ['7.4', '8.0', '8.1']