name: module-tests-master

on:
  workflow_call:
    inputs:
      module-id:
        description: Module ID.
        required: true
        type: string

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests.yml@main
    with:
      humhub-ref: >-
        ['master']
      php: >-
        ['7.4', '8.0', '8.1']